# This workflow runs on
#  * a `push` to any branch

name: CI

on:
  push:


jobs:
  # Documentation
  docs:
    name: Sphinx documentation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install package with dependencies
        run: |
          pip install -e .[docs]
      - name: Build documentation
        run: |
          sphinx-build -b html docs public
